jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - continue-on-error: true
      name: Setup JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Retrieve version
      run: 'echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >>
        $GITHUB_ENV

        '
    - continue-on-error: true
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      name: Write key
      run: "if [ ! -z \"${{ secrets.KEY_STORE }}\" ]; then\n  echo releaseStorePassword='${{\
        \ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties\n  echo releaseKeyAlias='${{\
        \ secrets.ALIAS }}' >> gradle.properties\n  echo releaseKeyPassword='${{ secrets.KEY_PASSWORD\
        \ }}' >> gradle.properties\n  echo releaseStoreFile='key.jks' >> gradle.properties\n\
        \  echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks\nfi\n"
    - continue-on-error: true
      name: Build with Gradle
      run: bash ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease
    - continue-on-error: true
      if: success()
      name: Upload built apk
      uses: actions/upload-artifact@v2
      with:
        name: Zhiliao_${{ env.VERSION }}
        path: ${{ github.workspace }}/app/build/outputs/apk/release
    - continue-on-error: true
      name: Send commit to telegram
      uses: appleboy/telegram-action@master
      with:
        document: ${{ github.workspace }}/app/build/outputs/apk/release/Zhiliao_${{
          env.VERSION }}.apk
        format: markdown
        message: 'New push to github!

          *${{ github.event.head_commit.message }}* by ${{ github.event.head_commit.author.name
          }}

          See commit detail [here](${{ github.event.head_commit.url }})

          Snapshot apk is attached

          '
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
  skipped:
    if: ${{ startsWith(github.event.head_commit.message, '[skip ci]') }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Send commit to telegram
      uses: appleboy/telegram-action@master
      with:
        format: markdown
        message: 'New push to github!

          *${{ github.event.head_commit.message }}* by ${{ github.event.head_commit.author.name
          }}

          See commit detail [here](${{ github.event.head_commit.url }})

          This push skipped building

          '
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___AndroidCI.yml
